services:
  app:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    container_name: laravel_app_dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./docker/develop/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - laravel-network
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_landing_dev
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver_dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/develop/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel_landing_dev
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - laravel-network
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: laravel_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

volumes:
  postgres_data_dev:

networks:
  laravel-network:
    driver: bridge